server:
  port: 8080
spring:
  application:
    name: sharding-springboot-mybatis
  profiles:
    active: company

sharding:
  jdbc:
    datasource:
      names: ds0
        # \u6570\u636E\u6E90ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.204.250:3306/study
        username: root
        password: root
    config:
      sharding:
        props:
          sql.show: true
        tables:
          #分表
          t_user:  #t_user\u8868
            key-generator-column-name: id  #\u4E3B\u952E
            #            ${begin..end}表示范围区间
            #            ${[unit1, unit2, unit_x]}表示枚举值
            actual-data-nodes: ds0.t_user${0..1}    #\u6570\u636E\u8282\u70B9,\u5747\u5300\u5206\u5E03
            table-strategy:  #\u5206\u8868\u7B56\u7565
              inline: #\u884C\u8868\u8FBE\u5F0F
                sharding-column: sex
                algorithm-expression: t_user${sex % 2}  #\u6309\u6A21\u8FD0\u7B97\u5206\u914D

---
sharding:
  jdbc:
    datasource:
      names: ds0
      ds0:
        url: jdbc:mysql://192.168.204.250:3306/study
spring:
  profiles: company

---
spring:
  profiles: home
sharding:
  jdbc:
    datasource:
      names: ds0
      ds0:
        url: jdbc:mysql://192.168.136.250:3306/study



