server:
  port: 8081
spring:
  profiles:
    active: home
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#下面这一行务必不能少，区分不同配置，而且必须是三个字符"-"
---
#home 在家时的配置
spring:
  profiles: home
  #这里面这个配置不生效了
  rabbitmq:
    host: 192.168.136.250
    port: 5672
    username: user_zjh
    password: user_zjh
    virtual-host: /user_zjh
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.136.250:3306/study

  jpa:
    #    database: MYSQL
    show-sql: true
    hibernate:
      #    create 启动时删数据库中的表，然后创建，退出时不删除数据表
      #    create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错
      #    update 如果启动时表格式不一致则更新表，原有数据保留
      #    validate 项目启动表结构进行校验 如果不一致则报错
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


---
#company 在公司时的配置
spring:
  profiles: company
  #这里面这个配置不生效了
  rabbitmq:
    host: 192.168.204.250
    port: 5672
    username: user_zjh
    password: user_zjh
    virtual-host: /user_zjh
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.204.250:3306/study

  jpa:
    #    database: MYSQL
    show-sql: true
    hibernate:
      #    create 启动时删数据库中的表，然后创建，退出时不删除数据表
      #    create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错
      #    update 如果启动时表格式不一致则更新表，原有数据保留
      #    validate 项目启动表结构进行校验 如果不一致则报错
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
