server:
  port: 8081
spring:
  profiles:
    active: company
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#自定义参数
rabbit: #MQ队列名称
  direct:
    exchange: async_exchange
    routing.key:
      key1: async_key1
      key2: async_key2
    queue:
      queue01: async_queue01
      queue02: async_queue02

#下面这一行务必不能少，区分不同配置，而且必须是三个字符"-"
---
#home 在家时的配置
spring:
  profiles: home
  #这里面这个配置不生效了
  rabbitmq:
    host: 192.168.136.250
    port: 5672
    username: user_zjh
    password: user_zjh
    virtual-host: /vhost_zjh
    publisher-confirms: false
    publisher-returns: true
    template:
      mandatory: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.136.250:3306/study

  jpa:
    #    database: MYSQL
    show-sql: true
    hibernate:
      #    create 启动时删数据库中的表，然后创建，退出时不删除数据表
      #    create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错
      #    update 如果启动时表格式不一致则更新表，原有数据保留
      #    validate 项目启动表结构进行校验 如果不一致则报错
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


---
#company 在公司时的配置
spring:
  profiles: company
  #这里面这个配置不生效了
  rabbitmq:
    host: 192.168.204.250
    port: 5672
    username: user_zjh
    password: user_zjh
    virtual-host: /vhost_zjh
    publisher-confirms: false
    publisher-returns: true
    listener:
      simple:
        concurrency: 10 #消费者数量
        max-concurrency: 10 #最大消费者数量
        prefetch: 1 #限流（消费者每次从队列获取的消息数量）
        auto-startup: true  #启动时自动启动容器
        acknowledge-mode: manual #开启ACK手动确认模式
    template:
      mandatory: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.204.250:3306/study

  jpa:
    #    database: MYSQL
    show-sql: true
    hibernate:
      #    create 启动时删数据库中的表，然后创建，退出时不删除数据表
      #    create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错
      #    update 如果启动时表格式不一致则更新表，原有数据保留
      #    validate 项目启动表结构进行校验 如果不一致则报错
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
